language: node_js
node_js:
- 8
cache:
  yarn: true
install:
- yarn
script:
- npm test
deploy:
  provider: npm
  email: stuwilliams47@gmail.com
  skip_cleanup: true
  api_key:
    secure: fZeX7FarWsnghahynY5P7RZUfd3S1CZ54wVQ8p7br7LCdRWvCffqOmcVkmspNOttaczIlSL9F3dDhMKJEmYnGiDeZb3kfewltZAJsya42fmETRF8FDPzBQvf34+XX4UvUxI+YvpIr1CiQUIEW9XPwBI6BGYWbbrBh5uQbxiLJlDVySsdtUisadL0zxrRt27eGVVNnngNSZiTmzqkRKy/Qk3/fjUne5IsMVaDR2HL9UDVXWp8PQRbb6+u2IvLdaH0/Oigm02BJiHoA1gV67IWcec9SUW1ESdTB6MWr2NL6QTRF5q/hZQGvSrVFQyig/sbbRTgMrP/jJgNHSKWVNedk0Do7QCcQXS8vD6yMZYW2dhN1hTX6VuG5PeEUHXQPNeO/ZiRwuw3VEaAiKTCuUg+mc2m9xIv6POqs5UxWsgdGbwj1WvfUrrpb7oZjbYcQ/4hHYwS2rY0PYKPDppngSsmGeZapOdAt0IZgRaNu+nugIyJL39eM1QTUAhlK3eEs10gttXwOov8qMTSibaylGmd3EJlhIJKeP9/pNAkszJ7TebErDvDEo3RI6mLGY91KTI42W1TbsgPduY2xGtFxxViY6FRvamLJWR+usa0mPdHnh1ea+REOo5m6GXIFbuo5Qiu/pWwVHkgLlGVc+1qm+NwsBBaon3mzb9DvVZ7Zwc1KCU=
  on:
    tags: true
    repo: stuart-williams/react-lrud
